#!/bin/sh
set -eu

export ROOMMATCH_API_URL="${ROOMMATCH_API_URL:-http://localhost:8080/api}"
export ROOMMATCH_WS_URL="${ROOMMATCH_WS_URL:-ws://localhost:3000}"
export ROOMMATCH_WEBSOCKET_URL="${ROOMMATCH_WEBSOCKET_URL:-ws://localhost:8080/ws-pure}"
export ROOMMATCH_FIREBASE_API_KEY="${ROOMMATCH_FIREBASE_API_KEY:-YOUR_API_KEY}"
export ROOMMATCH_FIREBASE_AUTH_DOMAIN="${ROOMMATCH_FIREBASE_AUTH_DOMAIN:-YOUR_AUTH_DOMAIN}"
export ROOMMATCH_FIREBASE_PROJECT_ID="${ROOMMATCH_FIREBASE_PROJECT_ID:-YOUR_PROJECT_ID}"
export ROOMMATCH_FIREBASE_STORAGE_BUCKET="${ROOMMATCH_FIREBASE_STORAGE_BUCKET:-YOUR_STORAGE_BUCKET}"
export ROOMMATCH_FIREBASE_MESSAGING_SENDER_ID="${ROOMMATCH_FIREBASE_MESSAGING_SENDER_ID:-YOUR_MESSAGING_SENDER_ID}"
export ROOMMATCH_FIREBASE_APP_ID="${ROOMMATCH_FIREBASE_APP_ID:-YOUR_APP_ID}"
export ROOMMATCH_FIREBASE_MEASUREMENT_ID="${ROOMMATCH_FIREBASE_MEASUREMENT_ID:-YOUR_MEASUREMENT_ID}"

envsubst '${ROOMMATCH_API_URL} ${ROOMMATCH_WS_URL} ${ROOMMATCH_WEBSOCKET_URL} ${ROOMMATCH_FIREBASE_API_KEY} ${ROOMMATCH_FIREBASE_AUTH_DOMAIN} ${ROOMMATCH_FIREBASE_PROJECT_ID} ${ROOMMATCH_FIREBASE_STORAGE_BUCKET} ${ROOMMATCH_FIREBASE_MESSAGING_SENDER_ID} ${ROOMMATCH_FIREBASE_APP_ID} ${ROOMMATCH_FIREBASE_MEASUREMENT_ID}' \
  < /usr/share/nginx/html/assets/env.template.js \
  > /usr/share/nginx/html/assets/env.js

exec /docker-entrypoint.sh "$@"
